## Ejercicio Repaso Árboles de Decisión

Simulando una competición de Kaggle, nos dan un df de train (``df_train``) y otro de test (``df_test``): 
1. Crea un modelo basado en árboles de decisión para predecir 'Target'
2. Crea otro modelo para predecir 'Target'. Esta vez usaremos un KNN, pero solo utilizaremos las variables que eran numéricas originalmente
3. ¿Con cuál de los 2 obtienes mejor resultado?
4. ¿Y si utilizamos un SVM?
4. Quedándote solo con las variables numéricas, utiliza un GridSearchCV para obtener la mejor combinación de parámetros de cada uno de ellos. ¿Cuál es el mejor ahora? Puedes utilizar pipelines con más elementos. Cuidado con el SVM, que dependiendo del kernel puede echarse mucho tiempo

In [2]:
import pandas as pd

In [3]:
df_train = pd.read_csv("../01_Supervisado/4-Decision Trees/ejercicios/data/adult_train.csv", sep=';')
df_test = pd.read_csv("../01_Supervisado/4-Decision Trees/ejercicios/data/adult_test.csv", sep=';').drop(0)

dic_tar = {
    ' >50K': 1,
    ' >50K.': 1,
    ' <=50K': 0,
    ' <=50K.': 0
}

df_train['Target'] = df_train['Target'].apply(lambda x: dic_tar[x])
df_test['Target'] = df_test['Target'].apply(lambda x: dic_tar[x])

num_cols = df_train.dtypes[df_train.dtypes != 'object'].index.tolist()
for col in num_cols:
    df_test[col] = df_test[col].astype(int)

## Regresión con árboles de decisión

1. Partiendo del DataFrame ``df_temps``, trata de predecir la columna ``actual``. Estamos ante un problema de regresión.
2. Utiliza un GridSearchCV para encontrar la mejor combinación de parámetros con la que obtengas el mejor RMSE
3. Saca la matriz de confusión del modelo

*NOTA*: Utiliza una división train/test del 70/30

In [14]:
df_temps = pd.read_csv("../01_Supervisado/4-Decision Trees/ejercicios/data/temps.csv", sep=',')
df_temps = df_temps[[col for col in df_temps.columns if 'forecast' not in col]]
df_temps

     year  month  day   week  temp_2  temp_1  average  actual  friend
0    2016      1    1    Fri      45      45     45.6      45      29
1    2016      1    2    Sat      44      45     45.7      44      61
2    2016      1    3    Sun      45      44     45.8      41      56
3    2016      1    4    Mon      44      41     45.9      40      53
4    2016      1    5   Tues      41      40     46.0      44      41
..    ...    ...  ...    ...     ...     ...      ...     ...     ...
343  2016     12   27   Tues      42      42     45.2      47      47
344  2016     12   28    Wed      42      47     45.3      48      58
345  2016     12   29  Thurs      47      48     45.3      48      65
346  2016     12   30    Fri      48      48     45.4      57      42
347  2016     12   31    Sat      48      57     45.5      40      57

[348 rows x 9 columns]